@echo off
mode con cols=100 lines=25 & color 0B
ECHO 01
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
ECHO 02
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
ECHO 03
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
ECHO 04
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
ECHO 05
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
ECHO 06
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
start "" chrome https://villains-libdrive.herokuapp.com
TimeOut /T 10 /NoBreak>NUL
start "" Firefox https://villains-libdrive.herokuapp.com
